max_width = 100
tab_spaces = 4
hard_tabs = false
edition = "2021"
fn_single_line = false
blank_lines_upper_bound = 2
blank_lines_lower_bound = 1
reorder_impl_items = true
struct_field_align_threshold = 0
group_imports = "Std"
use_small_heuristics = "Max"